### ISSUE TITLE
Problema con el modulo clickderecho.py

### ISSUE THREAD

**Issue by cbordolli** [renzosdd/APPsico#2]
En MAC no se ejecuta, revisar el modulo por si alguna libreria se debe llamar distinto o por la diferencia de versiones.

**Comment by renzosdd** [comment]
Describen el problema y posibles soluciones
https://stackoverflow.com/questions/30668425/tkinter-right-click-popup-unresponsive-on-osx

**Comment by renzosdd** [comment]
### Problema solucionado
**se agrega la comprobación de sistema operativo agregando el siguiente código:**

1. Importamos de la librería sys el modulo platform: 
`from sys import platform as _platform`

2. agregamos el siguiente codigo de comprobación:     
```
if _platform == "linux" or _platform == "linux2":
        return "linux"
    elif _platform == "darwin":
        return "mac"
    elif _platform == "win32":
        return "win32"
    elif _platform == "win64":
        return "win64"

```
