### ISSUE TITLE
Ingreso de nombre y apellido de paciente

### ISSUE THREAD

**Issue by jsmelli29** [renzosdd/APPsico#4]
Se pueden ingresar 2 pacientes con todos los datos iguales y al no tener CI u otro campo visible que sean distintos se puede dificultar saber cual es cual

**Comment by renzosdd** [comment]
Se soluciona agregando la siguiente linea a alta pacientes:

`        if self.pacientes.consulta("SELECT * FROM pacientes WHERE nombre = '"+self.nombre.get().capitalize() +"' AND apellido = '"+self.apellido.get().capitalize()+"' AND usuario = '"+self.usuario+"'"):
            messagebox.showinfo("Error", "Ya existe un paciente con el mismo nombre y apellido")
            ok=False`
